version: 2

models:
  - name: customers
    config:
      schema: trusted_data_flachavanne2
    columns:
      - name: customer_id
        description: Id del customer
        tests:
          - not_null
      - name: customer_unique_id
        description: Id unico del customer
        tests:
          - not_null
      - name: customer_zip_code_prefix
        description: ZIP Code del customer
      - name: customer_city
        description: Descripcion de la city del customer i.e (ACU, ICO, IPE)
      - name: customer_state
        description: Estado del customer i.e (RN, CE, RS)
  - name: geolocation
    config:
      schema: trusted_data_flachavanne2
    columns:
      - name: GEOLOCATION_ZIP_CODE_PREFIX
        description: ZIP Code 
        tests:
          - not_null
      - name: GEOLOCATION_LAT
        description: Latitud del zip
        tests:
          - not_null
      - name: GEOLOCATION_LNG
        description: Longitud del zip
        tests:
          - not_null
      - name: GEOLOCATION_CITY
        description: Ciudad del zip
      - name: GEOLOCATION_STATE
        description: Estado del zip
  - name: order_items
    config:
      schema: trusted_data_flachavanne2
    columns:
      - name: ORDER_ID
        description: identificador de la orden 
        tests:
          - not_null
      - name: ORDER_ITEM_ID
        description: identifica veces que aparece cada producto
      - name: PRODUCT_ID
        description: identificador del producto
      - name: SELLER_ID
        description: identificador del seller   
      - name: SHIPPING_LIMIT_DATE
        description: fecha límite de envío 
      - name: PRICE
        description: precio unitario de cada order_item 
      - name: FREIGHT_VALUE
        description: costo del envío de cada order_item 
  - name: sellers
    config:
      schema: trusted_data_flachavanne2
    columns:
      - name: SELLER_ID
        description: identificador del seller
        tests:
          - not_null
      - name: SELLER_ZIP_CODE_PREFIX
        description: zipcode del seller
      - name: SELLER_CITY
        description: ciudad del seller
      - name: SELLER_STATE
        description: estado del seller
  - name: products
    config:
      schema: trusted_data_flachavanne2
    columns:
      - name: PRODUCT_ID
        description: identificador del producto
        tests:
          - not_null
      - name: PRODUCT_CATEGORY_NAME
        description: nombre de la categoria
      - name: PRODUCT_NAME_LENGHT
        description: caracteres del nombre del producto
      - name: PRODUCT_DESCRIPTION_LENGHT
        description: caracteres del nombre del producto   
      - name: PRODUCT_PHOTOS_QTY
        description: Q de imagenes asociada al producto
      - name: PRODUCT_WEIGHT_G
        description: peso del producto en gramos 
      - name: PRODUCT_LENGTH_CM
        description: largo del producto en centímetros 
      - name: PRODUCT_HEIGHT_CM
        description: alto del producto en centímetros
      - name: PRODUCT_WIDTH_CM
        description: ancho del producto en centímetros
  - name: product_category_name_translation
    config:
      schema: trusted_data_flachavanne2
    columns:
      - name: PRODUCT_CATEGORY_NAME
        description: nombre de la categoría del producto
        tests:
          - not_null
      - name: PRODUCT_CATEGORY_NAME_ENGLISH
        description: nombre en inglés de la categoría del producto
  - name: orders
    config:
      schema: trusted_data_flachavanne2
    columns:
      - name: ORDER_ID
        description: identificador de la orden
        tests:
          - not_null
      - name: CUSTOMER_ID
        description: identificador del cliente
      - name: ORDER_STATUS
        description: estado de la orden 
      - name: ORDER_PURCHASE_TIMESTAMP
        description: momento de compra (yyyy-mm-dd hh-mm-ss UTC) 
      - name: ORDER_APPROVED_AT
        description: momento de aprobación de la orden (yyyy-mm-dd hh-mm-ss UTC) 
      - name: ORDER_DELIVERED_CARRIER_DATE
        description: momento de entrega a flete (yyyy-mm-dd hh-mm-ss UTC)  
      - name: ORDER_DELIVERED_CUSTOMER_DATE
        description: momento de entrega a cliente (yyyy-mm-dd hh-mm-ss UTC)  
      - name: ORDER_ESTIMATED_DELIVERY_DATE
        description: momento de entrega estimado a cliente (yyyy-mm-dd hh-mm-ss UTC)