version: 2

sources:
  - name: fran_ecommerce_ecommerce_prd
    schema: fran_ecommerce_ecommerce_prd
    tables:
    - name: customers
    - name: geolocation
    - name: order_items
    - name: order_payments
    - name: order_reviews
    - name: orders
    - name: product_category_name_translation
    - name: products
    - name: sellers